apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  namespace: my-kafka-project
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7.30
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: debezium
          - name: MYSQL_USER
            value: mysqluser
          - name: MYSQL_PASSWORD
            value: mysqlpw
        ports:
        - containerPort: 3306
          name: http
          protocol: TCP
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/mysql.cnf
          subPath: mysql.cnf
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
          items:
          - key: mysql.cnf
            path: mysql.cnf

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: my-kafka-project
spec:
  ports:
  - name: http
    port: 3306
    protocol: TCP
    targetPort: http
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP

